services:
  - type: web
    name: south-sudan-horizons-backend
    env: node
    repo: https://github.com/longmaker2/south_sudan_horizons
    branch: main
    rootDir: backend
    buildCommand: yarn build
    startCommand: yarn start
    plan: free # Adjust based on your Render plan
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false # Set manually in Render dashboard
      - key: MONGO_URI
        sync: false # Set manually in Render dashboard
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false # Set manually in Render dashboard
      - key: ADMIN_KEY
        sync: false # Set manually in Render dashboard
      - key: Guides_KEY
        sync: false # Set manually in Render dashboard
