export const STRIPE_PUBLISHABLE_KEY =
  import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY ||
  "pk_test_51R1V6q07gKx24rpiZjXRcf84SdMraXj90Ze5W8ScYyWfs6GrimmkipURPoNoinDrVC7gu4oLnobwxlPMPXBvwOJz00iMMbS7qK";
